### ISSUE TITLE
VCR is causing the spec to break

### ISSUE THREAD

**Issue by nkroker** [vcr/vcr#1017]
I'm not sure about what is wrong with the test case here but seems like VCR is not able to handle the request for this specific use-case

### Screenshot

<img src="https://github.com/vcr/vcr/assets/26537166/ecdccef8-4d25-4ee2-9757-4b51efcc2b3e" width="65%" height="65%">

---

### Here's my VCR configuration and the affected cassette along with the spec
[returns_historic_data.yml.txt](https://github.com/vcr/vcr/files/14805405/returns_historic_data.yml.txt)

``` ruby
  VCR.configure do |config|
    config.cassette_library_dir = "#{::Rails.root}/spec/cassettes"
    config.hook_into :webmock
    config.ignore_localhost = true
    config.configure_rspec_metadata!
  end
```

```ruby
  describe '#get_historic_aqi' do
    context 'when location id is provided' do
      let!(:location) { create(:location, id: 2) }

      it 'returns historic data', :vcr do
        response = PollutionStatService.get_historic_aqi(location_id: location.id)

        expect(response).to have_key('coord')
        expect(response).to have_key('list')
      end
    end
  end
```

---

Ruby `3.1.4`
Gem `vcr (6.2.0)`
Rails `rails (7.1.3.2)`
Rspec `rspec-core (3.9.3)`

**Comment by andrehjr** [comment]
I think you're getting this error because the URI stored on the recorded cassette is different from the error you are getting. And you have 'record: :once' configured?  

On the cassette, you have:
```
uri: http://api.openweathermap.org/data/2.5/air_pollution/history?appid=967067df-f7ed-4223-a979-cb71082ba3f6&end=1711723167&lat=51.5073&lon=-0.1276&start=1709131167
```

on the error above you have:

<img width="1392" alt="image" src="https://github.com/vcr/vcr/assets/16997/c59a0fb4-dd64-45f5-99b8-49b30b6576d0">

So I think you have a few options. 
- Make VCR record new episodes. Adding this to the config:  `c.default_cassette_options = { record: :new_episodes }`. The problem with this is that if every spec execution changes the id. it will make the cassette get bigger every single time.
- Make the cassette ERB dynamic https://benoittgt.github.io/vcr/#/cassettes/dynamic_erb?id=dynamic-erb-cassettes just so you can match it with anything
- Or you can make sure the URI always stays the same for this spec, and you should be good.

**Comment by nkroker** [comment]
Thanks it worked
