### ISSUE TITLE
Proposal: Move allow_http_connections_when_no_cassette to a local scope

### ISSUE THREAD

**Issue by maurogeorge** [vcr/vcr#387]
Guys,

I love VCR. But in some projects I start working, I see this config `allow_http_connections_when_no_cassette`, but used for wrong purposes.

VCR has a awesome feature, who is tell the user when your spec is accessing network. But if I was working in a project with the `allow_http_connections_when_no_cassette` as `true`, I lost this feature.

My proposal is to pass this config as a param on the VCR block, to be more close of the context of the spec, like the [WebMock.allow_net_connect!](https://github.com/bblimke/webmock#real-requests-to-network-can-be-allowed-or-disabled).

What you guys think?

**Comment by machty** [comment]
I believe I'd like this feature as well, though for possibly different reasons. Specifically, I want to be able to set `allow_http_connections_when_no_cassette = false` so that, by default, all outbound HTTP requests must be wrapped in `VCR.use_cassette`; this enforces that no unexpected outbound requests sneak into the system for tests that never intended to cause those requests to happen. 

That said, there are a handful of specs where I want to allow unlimited outbound access (for certain complicated acceptance/integration tests). In these cases I don't want `use_cassette` but would rather just be able to set `allow_http_connections_when_no_cassette` to true for only a handful of test cases. Is there no elegant way to do this?

I tried

```
  around(:each) do |example|
    begin
      VCR.config { |c| c.allow_http_connections_when_no_cassette = true }
      example.run
    ensure
      VCR.config { |c| c.allow_http_connections_when_no_cassette = false }
    end
  end
```

which seemed to semi-work but felt incorrect and I'm not sure what havoc I'm wreaking by reopening a config block mid-test.

**Comment by StanBright** [comment]
hey @machty, did you manage to find an elegant solution?
