### ISSUE TITLE
Is it possible to disable VCR based on type of spec?

### ISSUE THREAD

**Issue by aaronmcadam** [vcr/vcr#427]
Hi there,

I've just started using `VCR` again today for my feature specs. I've already got a whole list of stubs created with `WebMock` that I already use for my unit tests so I can easily control the data in order to test edge cases. I'm struggling to turn off `VCR` for those tests though.

Here's what I'm trying:

In `spec_helper`:

```
  config.before do |example|
    unless example.metadata.key?(:vcr)
      VCR.turn_off!(:ignore_cassettes => true)
    end
```

I've also tried `config.around` too, but that weirdly makes all my specs pass crazy fast regardless of correctness.

Then I call `VCR.turn_on!` in the feature spec, which runs perfectly fine:

```
require "spec_helper"

VCR.turn_on!
vcr_options = { record: :new_episodes }
feature "Visitor signs in", vcr: vcr_options do
  scenario "with valid email and password" do
    visit(sign_in_path)
    sign_in_as_admin

    user_is_signed_in
  end
  ...
```

But then I get an error when the full suite run hits a unit spec. The stack trace I get from hitting, say for example, a Controller spec is something like:

```
1) PostsController POST #create invalid attributes renders @post.errors as text
     Failure/Error: sign_in_as(build_stubbed(:admin))
     ArgumentError:
       VCR::Response initialized with an invalid body: {"access_token"=>"abcdef", "token_type"=>"bearer", "expires_in"=>7200, "refresh_token"=>nil, "scope"=>""}.
     # ./spec/controllers/posts_controller_spec.rb:5:in `block (2 levels) in <top (required)>'
```

The above is the content of the `WebMock` stub I've hand-rolled for authenticating in my controller specs.

Any pointers would be great as I really want to use VCR to remove the knowledge of data sources in my acceptance tests.

**Comment by candidosales** [comment]
Where use metadata in rspec?

**Comment by heaven** [comment]
This doesn't work for me. I've:
```ruby
require 'vcr'

VCR.configure do |c|
  c.cassette_library_dir = 'spec/vcr_cassettes'
  c.hook_into :webmock
  c.default_cassette_options = { allow_unused_http_interactions: false, re_record_interval: 7.days }
  c.ignore_localhost = true
  #c.debug_logger = $stdout
  c.before_http_request(:recordable?) do |request|
    puts "VCR #{request.method.upcase}: #{request.uri}"
  end
end

RSpec.configure do |config|
  config.around(:each, :vcr => true) do |example|
    if ex.metadata.key?(:vcr)
      example.run
    else
      WebMock.allow_net_connect!
      VCR.turned_off { example.run }
      WebMock.disable_net_connect!
    end
  end
end
```
What do I do wrong? How can I enable VCR *only* for examples I need?

And still getting:
```
VCR::Errors::UnhandledHTTPRequestError:


       ================================================================================
       An HTTP request has been made that VCR does not know how to handle:
         POST https://api.stripe.com/v1/tokens
```

**Comment by lastobelus** [comment]
The docs at https://relishapp.com/vcr/vcr/v/3-0-3/docs/test-frameworks/usage-with-rspec-metadata are a little misleading. Until I found this ticket I assumed after reading them that`vcr` would only be enabled in specs labeled `:vcr`. If `vcr` is always on, why do we need the `:vcr` metadata tag?

**Comment by fikrikarim** [comment]
Is there any chance to reopen this issue? 
> The docs at https://relishapp.com/vcr/vcr/v/3-0-3/docs/test-frameworks/usage-with-rspec-metadata are a little misleading. Until I found this ticket I assumed after reading them thatvcr would only be enabled in specs labeled :vcr. If vcr is always on, why do we need the :vcr metadata tag?

**Comment by krainboltgreene** [comment]
@fikrikarim Mind posting your rspec setup pre and post? A few things:

  1. By default vcr is not enabled, it can't be, you have to tell it to listen.
  2. VCR would only add an extended amount of time to tests if the tests were run on a filesystem that had limited resources, since it does *nothing but* store files on a network request.
  3. VCR should by configuration be setup to only allow http connections in local development, not CI.

**Comment by fikrikarim** [comment]
Hi @krainboltgreene. First of all thank you so much for such an immediate response :)

Here's our `vcr.rb`:
```ruby
VCR.configure do |c|
  c.cassette_library_dir = 'spec/fixtures/vcr'
  c.allow_http_connections_when_no_cassette = false
  c.hook_into :webmock
  c.ignore_localhost = true

  c.default_cassette_options = { record: :none, match_requests_on: [:path] }
end
```

1. I tried to run a simple spec:
```ruby
it 'user can see the modal displaying all the lesson items with the same type' do
  url = URI.parse('http://www.example.com/index.html')
  req = Net::HTTP::Get.new(url.to_s)
  res = Net::HTTP.start(url.host, url.port) {|http|
    http.request(req)
  }
  puts res.body
end
```
and got an error:
```bash
VCR::Errors::UnhandledHTTPRequestError:
================================================================================
      An HTTP request has been made that VCR does not know how to handle:
        GET http://www.example.com/index.html
```
Previously I assumed VCR by default only run on spec with `:vcr` tag and just ignore the other specs without `:vcr` tag. Is there any wrong with our configuration? We mostly use the configuration from the documentation.

2. Well I don't mind whether VCR hooks into every spec, but I noticed testing time increased when I included the VCR configuration on some group specs (434 system specs) that doesn't need VCR: ~9min without VCR config vs ~13 min with VCR config. Well we didn't expect it since the specs that use VCR are on the unit specs and shouldn't affect the performance of the system specs.

That's when I bumped into this thread. I'm trying to add additional RSpec code:
```ruby
RSpec.configure do |config|
  config.around(:each) do |example|
    vcr = example.metadata[:vcr]

    if vcr.nil?
      WebMock.allow_net_connect!
      VCR.turned_off { example.run }
      WebMock.disable_net_connect!
      next
    end
  end
end
```
But I'm still testing whether the time become closer to ~9min or ~13 min.

3. Hmm I'm sorry I'm not really sure about this one. But I think our VCR configuration is similar for both local and CI.

Anyway thanks again for the response :)

**Comment by krainboltgreene** [comment]
Can you show us the entire rails_helper?

**Comment by fikrikarim** [comment]
Sorry, I'm not sure I can upload all the RSpec configuration, because we have ~20 support files that configure the RSpec. I tried to search each file that might contribute to the slowness of the test. One thing that seems suspicious is the `fake_stripe.rb`:
```ruby
require 'fake_stripe'

RSpec.configure do |config|
  config.before(:each) do
    FakeStripe.stub_stripe
  end
end
```
It seems suspicious because on the source code fake_stripe [initialize WebMock](https://github.com/thoughtbot/fake_stripe/blob/master/lib/fake_stripe/initializers/webmock.rb). In the end by disabling WebMock for system specs that doesn't require vcr or stripe stub, we managed to reduce the spec testing time on CI from ~30min to ~7min:
```ruby
config.around(:each) do |example|
  vcr = example.metadata[:vcr]

  if vcr.nil?
    WebMock.disable!
    VCR.turned_off { example.run }
    WebMock.enable!
    next
  end
end
```
It's our fault in the first place the testing time reach ~30min. So it's a huge comeback to make the time become ~7min. But we're still not sure why by disabling WebMock can reduce so much testing time.

I think we're already out of topic from this issue, and the problem isn't on VCR, so I guess you can close this issue. I'm just writing this maybe to help someone who might experience the same thing.

Again thank you @krainboltgreene for your attention!
