### ISSUE TITLE
Remove Redis from tests, add as an example

### ISSUE THREAD

**Issue by krainboltgreene** [vcr/vcr#463]
So I was a bit surprised that apparently VCR supports Redis as a storage mechanism for VCR cassettes. It's kinda cool as a concept, though dubious. I like to look at these kinds of baggage with the reverse situation: Would I :+1: a pull request supporting redis as a storage engine?

The answer is _sorta_. I'd be totally cool with `vcr-redis.gem`, or anything similar. So I can't help but think it probably doesn't belong here.

This is a similar issue to #462.

**Comment by myronmarston** [comment]
> So I was a bit surprised that apparently VCR supports Redis as a storage mechanism for VCR cassettes.

VCR doesn't.  (Grep `lib` and you'll find no mention of redis).  VCR simply supports a persistence protocol that allows alternative persistence (rather than the file system to be used), and the easiest way I could find to demonstrate how that works in a cucumber scenario was to use Redis:

https://github.com/vcr/vcr/blob/master/features/cassettes/persistence.feature

Feel free to change how that feature is demonstrated and not use redis, of course.

**Comment by krainboltgreene** [comment]
Bleh, could have sworn I saw it in a lib directory file. You're absolutely correct.

**Comment by krainboltgreene** [comment]
I have to say the implementation for the persistence engines is pretty elegant.
