### ISSUE TITLE
Ruby versions to drop for testing

### ISSUE THREAD

**Issue by krainboltgreene** [vcr/vcr#464]
Current ruby versions we test:
- 1.8.7
- 1.9.2
- 1.9.3
- 2.0.0
- 2.1.0
- ree
- jruby-18mode
- jruby-19mode
- rbx-18mode
- rbx-19mode

We can still support any version, but removing some from active testing seems like something to review.

**Comment by krainboltgreene** [comment]
We're dropping 1.8.7, ree. Tenantively dropping jruby-18mode and rbx-18mode. I think jruby-18mode is probably something we NEED. Thoughts?

**Comment by myronmarston** [comment]
IMO, you shouldn't drop 1.8.7 versions until 3.0 -- if you don't have travis running against 1.8.7, it's too easy to accidentally break 1.8.7 support in a 2.x release, unless you use 1.8.7 locally as your primary ruby (which would be surprising!).  For RSpec, having 1.8.7 in our travis build matrix is hugely valuable as it catches 1.8.7-specific issues all the time.  REE could probably be dropped from the travis matrix anytime since it's not really a different version and I can't think of a single time the REE build caught an REE-specific failure.  I think of REE as being kinda like an alternate patch version of 1.8.7 and we don't build against all 1.8.7 patch levels, obviously.

jruby-18mode should be dropped at the same time as 1.8.7 (it's the JRuby equivalent), in VCR 3.0.  I guess you could drop it from the travis build matrix before 3.0 and still support it officially...but that seems kinda risky given that it's a completely different code base (written in a different language!) than MRI 1.8.7.

I've put many hours into trying to get consistent passing RBX builds for both VCR and RSpec and gave up long ago.  Up to you if you want to keep RBX in the build matrix at all.

Other things to consider dropping in VCR 3.0:

* Fakeweb support
* Support for Typhoeus <= 0.4.
* Support for Faraday <= 0.8.

**Comment by krainboltgreene** [comment]
I question the drop of jruby-18mode because it seems like 18mode of jruby is pretty much *the* jruby version. I asked in #jruby but the best they can say is they have significantly less 1.8.* bug reports anymore, so maybe it's OK to just support ci testing jruby-19mode.

**Comment by krainboltgreene** [comment]
Man, I had no idea fakeweb was that bad off.

**Comment by sigmavirus24** [comment]
So my opinion is that if you're not testing it you're not supporting it. We stopped testing on Py3.2 over on [requests](/kennethreitz/requests) and while the library continues to work there, we don't explicitly state anywhere that we support it. If you want to continue to claim to support 1.8, you should test against it.

**Comment by krainboltgreene** [comment]
Very good points. I'll probably revert when I get home.

**Comment by mcfiredrill** [comment]
Thoughts on dropping 1.9.2 for 3.0 ? It has reached EOL as well:
https://www.ruby-lang.org/en/news/2014/07/01/eol-for-1-8-7-and-1-9-2/

**Comment by krainboltgreene** [comment]
Whew. Good question. Likely the answer will be: Testing energy will be put towards latest version + common version (2.* & 1.9.* right now, 3.* & 2.* later) and branch specific fixes for outdated (1.8.6, 1.8.7, 1.9.1).

Of course this doesn't even get close to how I'll manage the non-CRuby strategies.

**Comment by krainboltgreene** [comment]
Right now my primary goal is getting payed to work on VCR part time.

**Comment by krainboltgreene** [comment]
I didn't, but we also stopped supporting anything less than LTS.
