### ISSUE TITLE
Rspec macro deprecation, what am I supposed to do instead?

### ISSUE THREAD

**Issue by Senjai** [vcr/vcr#508]
WARNING: VCR::RSpec::Macros is deprecated. Use RSpec metadata options instead `:vcr => vcr_options`

This is unclear, I still use the same options from the documentation. context "my thing", vcr: true.

What will this be deprecated for? What should I use instead.

**Comment by krainboltgreene** [comment]
Good question, can you paste the spec?

**Comment by galori** [comment]
Macros refer to the old syntax, example:

```
context "new employee" do
    use_vcr_cassette

    it 'adds a new employee' do
      expect(Employee.add_new_employee).to eq(true)
    end
  end
```

(specifically the `use_vcr_cassette` part).

The new syntax is 

```
context "new employee", vcr: true do
```

or even better

```
context "new employee", :vcr do
```

(see https://www.relishapp.com/vcr/vcr/v/2-5-0/docs/test-frameworks/usage-with-rspec-metadata)

If you're getting the warning, its either because you're using the old macros / syntax in your tests (the `use_vcr_casette` directive), or its possible you've already removed all of those references from all of your tests, but you're still enabling the macros in your rspec config. Look for:

```
RSpec.configure do |c|
  c.extend VCR::RSpec::Macros
end
```

If it is none of those things, re-open this ticket and provide example code to reproduce! 

Thanks!

**Comment by hakunin** [comment]
Hey guys, I have a time sensitive request and I use this:
```
      use_vcr_cassette 'trello_import_uploads' do |cassette|
        travel_to cassette.originally_recorded_at
      end
```

Is this still possible with the new syntax?

**Comment by urkle** [comment]
@hakunin to convert that you can't use the options but you can use an around in Rspec.

```ruby
    around do |example|
      VCR.use_cassette('trello_import_uploads') do |cassette|
        travel_to(cassette.originally_recorded_at) do
          example.call
        end
      end
    end
```

**Comment by romanshorin** [comment]
Hi guys! Previously if I put `use_vcr_cassette` into a context, it will create one vcr cassette for a context but now it creates one vcr cassette per rspec `it`. Are there any ways to restore previous behaviour?
