### ISSUE TITLE
Need a record option that deletes unused interactions (or starts from scratch)

### ISSUE THREAD

**Issue by ronwsmith** [vcr/vcr#587]
Working with a large system that has a lot of API dependencies.  As interactions change, we have been using `record: all` to refresh the existing cassettes.

Recently, we discovered strange behavior when refreshing cassettes that way, but the issue went away when deleting the cassette file completely, and then re-recording it.  Not sure if it was file length or what, but instead of debugging that, I'd rather have a way to completely record new cassettes from scratch.

We rarely, if ever, need to keep old unused interactions in the cassette and had assumed it was overwriting the existing cassette until we ran into the aforementioned issue.

**Comment by ecnalyr** [comment]
I think there are two topics here, could you clarify a few things for me?

**1)** A possible bug associated with the `:all` record mode.
> Need a record option that deletes unused interactions

> Recently, we discovered strange behavior when refreshing cassettes that way, but the issue went away when deleting the cassette file completely, and then re-recording it.

> and had assumed it was overwriting the existing cassette

Are you saying that it appears that when you used `record: all` to update your cassettes, some of the cassettes kept old requests in the cassette file even though that old request is no longer used by the cassette? 

If that's the case, it looks like we may just need to be clearer i[n the documentation](http://www.relishapp.com/vcr/vcr/v/3-0-3/docs/record-modes/all):

> The :all record mode will:
> - Record new interactions.
> - Never replay previously recorded interactions.
> This can be temporarily used to force VCR to re-record
a cassette (i.e. to ensure the responses are not out of date)
or can be used when you simply want to log all HTTP requests.

Deleting unused requests is not a documented feature of the `:all` record mode.  Instead, VCR ensures that pre-existing recorded-requests are not played back when `:all` record mode is in use.

If your tests pass when in `:all` record mode, but then fail after the cassettes are updated because of an old request lingering around it's obviously undesirable and I'd like to see more details.

It is hard to say whether or not that is a problem with VCR or your local app without seeing an example.  If you ran into the issue, others may have experienced it as well, I know this issue is several months old, but **if you could provide more details that could allow me to reliably reproduce the issue, we could investigate if it's something VCR should handle or if it's just something we should warn about in VCR's documentation**.

If my understanding is inaccurate, please correct me.

**2)** A request for a new feature.

> We rarely, if ever, need to keep old unused interactions in the cassette and had assumed it was overwriting the existing cassette. . .

I have felt that way before, I don't know about the history of VCR to know how the community handles these lingering unused requests.

>  I'd rather have a way to completely record new cassettes from scratch.

I'm (I'm sure others would be too) weary of introducing this kind of destructive functionality.  Something as simple as `if this cassette exists, delete it, then record all` may be reasonable. . .

But guaranteeing that all unused cassettes are removed when a command is run seems like it may be too challenging to do safely.  Imagine a User runs only one file from their suite with the new destructive re-record option. . .  

If there is real demand for this functionality I would probably look at writing a safe-ish version myself, but destroying all of your local cassettes is normally akin to deleting one or two directories worth of files - something that would probably be done by devs on their own long before they look for the existence of a mode in VCR itself that would destroy unused cassettes before re-creating them.

I personally don't feel like there's much real need for this kind of feature beyond what the `:all` record mode already does.  Please let me know if you feel otherwise, _especially_ since you've had a few months since the creation of this issue to 'sleep on it.'

**Comment by ronwsmith** [comment]
Appreciate the detailed follow-up @ecnalyr

1) Yes, you are correct in your interpretation.  It happens over time and we've since come up with a workaround so it may never occur for us again.

You can likely replicate by:
* Running a spec with VCR
* Manually edit the URL in the cassette
* Run the spec again

If it adds a request/response to the cassette, that will confirm my suspicions.

2) If I'm the only one reporting this issue, perhaps it's the evolving SOA environment I'm working within and others won't have the issue.  No need to fix something unless it's a larger issue.

Here are my two relevant workarounds for others that stumble across this issue:

```ruby
USED_CASSETTES = []

module CassetteCleaner
  def insert_cassette(name, options = {})
    current_cassette = VCR::Cassette.new(name, options).file
    # NOTE: default_cassette_options[:record] is set to :all when ENV['REFRESH'] is set
    # we want to override any current cassette on file when ENV['REFRESH'] is set
    if configuration.default_cassette_options[:record] == :all
      File.delete(current_cassette) if File.exist?(current_cassette)
    else
      USED_CASSETTES << current_cassette
    end

    super
  end
end
VCR.extend(CassetteCleaner)
```

```ruby
def clean_unused_cassettes
  return unless ENV['CLEAN_UP_UNUSED_CASSETTE']
  unused_cassettes = Dir.glob('spec/support/cassettes/**/*.yml').map { |d| File.expand_path(d) } - USED_CASSETTES

  unless unused_cassettes.empty?
    unused_cassettes.each { |v| File.delete(v) }
    puts unused_cassettes.inspect
  end
end
```

```ruby
RSpec.configure do |config|
  config.after(:suite) do
    clean_unused_cassettes
  end
end
```

**Comment by ronwsmith** [comment]
Workaround exists and no one else is reporting at the moment.  Closing issue.
