### ISSUE TITLE
Expired cassettes allowed to record with record: :none

### ISSUE THREAD

**Issue by Billiam** [vcr/vcr#687]
If a cassette has previously been recorded, but has expired, setting the record mode to `:none` still allows requests to go through, and updates the cassette (in versions 3.0.3 and 4.0.0).

```ruby
VCR.use_cassette('example', re_record_interval: 1.second) do
    Net::HTTP.get_response('example.com', '/bar')
end
sleep 5
VCR.use_cassette('example', record: :none, re_record_interval: 1.second) do
    Net::HTTP.get_response('example.com', '/bar')
end
```
**Expectation:** Example cassette is initially recorded, and the second attempt to use the (now expired) cassette when the record mode is `:none` raises an `UnhandledHTTPRequestError`

**Behavior:** Both requests succeed, and the example request is updated.

**Comment by coding-bunny** [comment]
I know this issue is old, but I think I'm running into this problem as well now, when using `Timecop` to freeze a test and having the `re_record_interval` set. Even when running with the `:none` option, VCR keeps updating the cassettes.

And the response part is being updated, as the requests themselves don't change.

**Comment by coding-bunny** [comment]
So I changed our VCR settings by removing `:re_record_interval` and setting the record mode to `:once` and now VCR is no longer updating the cassettes but actually re-using them.

I feel when using Timecop to freeze time for specific requests, VCR really doesn't play nice.
