### ISSUE TITLE
CI: JAVA_OPTS shell warning

### ISSUE THREAD

**Issue by olleolleolle** [vcr/vcr#752]
[This Travis job](https://travis-ci.org/vcr/vcr/jobs/538555567#L428) has the following output

```
Setting environment variables from repository settings
$ export CODECLIMATE_REPO_TOKEN=[secure]
$ export JAVA_OPTS=-client -XX:+TieredCompilation -XX:TieredStopAtLevel=1
/home/travis/.travis/functions: line 104: export: `-XX:+TieredCompilation': not a valid identifier
/home/travis/.travis/functions: line 104: export: `-XX:TieredStopAtLevel=1': not a valid identifier
```

Could it be that there are Travis Settings-set Environment Variables, which lack quoting around the full value of `JAVA_OPTS`?

I have no visibility into that screen on Travis, so I can't view those settings.

<details>

The `JAVA_OPTS` value is set fully quoted in the `scripts/ci.sh`, to have the above value.

</details>

**Comment by krainboltgreene** [comment]
@olleolleolle If there is, we can't see  it anymore. Maybe travis changed that layer and broke the values?

Honestly, given the company's situation, I would much rather us exist on circle ci, but VCR's current testing situation is precarious at best due to the meta nature of a testing library that talks to a network.

**Comment by krainboltgreene** [comment]
To be clear: Travis environment variables are completely one way from the interface.

**Comment by LoveConnie** [comment]
Duplicate of #493

**Comment by olleolleolle** [comment]
Closing this issue as we no longer run JRuby tests. 🎉
