### ISSUE TITLE
Warnings about not used cassettes

### ISSUE THREAD

**Issue by goozzik** [vcr/vcr#759]
I often find myself in situation where somebody (sometimes me 😳 ) gets rid of some test(s) which results in leftover VCR cassettes. This quite often slips through CR because it is not that easy to spot.

I would like to have some option to enable warnings/exception raising when situation like this happen. It could be new configurable:

```ruby
VCR.configure do |config|
  config.warn_about_unused_cassettes = true
end
```

The check should run only when whole test suite is run. 

I found that I'm not the only facing the issue and people were asking in the past for something that would solve this particular issue https://github.com/vcr/vcr/issues/283.

**Comment by krainboltgreene** [comment]
I've solved this at a previous company, but it's not an easy solution. It's effectively the same as asking 'Which method doesn't get called in my codebase?'

The answer gets fuzzier the less code get run! It's actually impossible to know as it's impossible to know if "all things that use VCR have run".

Here's how I solved this:

  1. Make sure the tests you're about to run have no modifiers to rspec (`:focus`, a path, etc)
  2. Grab all VCR file paths into a list
  3. As VCR is called, check to see if the path expected is inside the list. If it is, then remove it from the list. If not, then explode because you clearly didn't do #1.
  4. At the end of the run, print out a list of all the remaining cassettes.

Things to note: Those remaining cassettes might just not have been used because of randomness in a test or a race condition. There's no way to know.
