### ISSUE TITLE
Cucumber 5.2.0 no longer supports the .feature method to get the name of a test case, used in "use_scenario_name"

### ISSUE THREAD

**Issue by dannyvanhoof** [vcr/vcr#843]
The VCR method https://github.com/vcr/vcr/blob/v6.0.0/lib/vcr/test_frameworks/cucumber.rb#L51-L52 still uses the "feature" method, which is no longer supported by cucumber 5.2.0.
Are there any plans to fix this issue?

**Comment by olleolleolle** [comment]
Do you have a proposed fix?  Yes, were interested in having that working also with that version!

**Comment by luke-hill** [comment]
So the main issue of this (or the crux of it), boils down to the internals i.e. the way in which cucumber "works". 

From v4, the methods available during the hook execution changed, because fundamentally the block arg is slightly different now. (Interestingly enough, the scenario name apparently was never correct, it was more like a test_case but that's not the point here).

This new block arg has different methods so consequently, you need to use the new methods. The likelihood of it being reverted is slim. This new block arg is representative of the new "pickle" instead of the entire AST.

What you can get that is "similar" is the file name. I extend using a patch that looks like the following

```
# frozen_string_literal: true

module Cucumber
  module Core
    module Test
      class Case
        def feature_file_name
          feature_file_path.split("/").last.split(".").first
        end

        private

        def feature_file_path
          location.to_s
        end
      end
    end
  end
end
```

**Comment by brasmusson** [comment]
This change in https://github.com/vcr/vcr/blob/v6.0.0/lib/vcr/test_frameworks/cucumber.rb#L51-L52
```
            elsif scenario.respond_to?(:feature)
              [ scenario.feature.name.split("\n").first,
                scenario.name.split("\n").first
              ].join("/")
            else
              [ scenario.location.file.split("/").last.split(".").first,
                scenario.name.split("\n").first
              ].join("/")
            end
```
should use the feature file basename (without extension) instead of feature name in cases when the feature cannot be accessed (that is Cucumber-Ruby >= 4.0).

**Comment by olleolleolle** [comment]
🌟 Thanks, Cucumber experts! 🌟
